name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  # Paranoia - assert tests pass
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    needs: [tests]
    uses: dairiki/gh-workflows/.github/workflows/publish-to-pypi.yml@v1
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
